<?php

return [

    'name' => 'A2Z Solutions',
    'name_ar' => 'A2Z Solutions',

    'brand' => [
        'letter_a' => 'A',
        'middle' => '2',
        'letter_z' => 'Z',
        'suffix' => ' Solutions',
    ],
    'tagline' => 'نحن هنا لتمكين طموحاتك التقنية من خلال الابتكار والخبرة العميقة.',

    'contact' => [
        'email' => 'ahmadqatea023@gmail.com',
        'phone' => '+963993511250',
        'whatsapp' => '963993511250',
        'location' => 'سوريا، محافظة إدلب، كرباط',
        'coordinates' => [
            'lat' => 35.93842120265023,
            'lng' => 36.64029414273561,
        ],
    ],

    'social' => [
        [
            'label' => 'فيسبوك',
            'icon' => 'groups',
            'href' => 'https://www.facebook.com/',
        ],
        [
            'label' => 'إنستغرام',
            'icon' => 'camera',
            'href' => 'https://www.instagram.com/',
        ],
        [
            'label' => 'الموقع الإلكتروني',
            'icon' => 'web',
            'href' => 'https://a2z-solutions.com/',
        ],
    ],

    'navigation' => [
        ['label' => 'الرئيسية', 'route' => 'home', 'href' => '/'],
        ['label' => 'الخدمات', 'route' => 'services', 'href' => '/services'],
        ['label' => 'الأعمال ودراسة الحالة', 'route' => 'projects', 'href' => '/projects'],
        ['label' => 'عن الشركة', 'route' => 'knowledge', 'href' => '/knowledge#about'],
        ['label' => 'مركز المعرفة', 'route' => 'knowledge', 'href' => '/knowledge'],
        ['label' => 'تواصل معنا', 'route' => 'contact', 'href' => '/contact'],
    ],

    'legal_links' => [
        ['label' => 'سياسة الخصوصية', 'href' => '#privacy'],
        ['label' => 'شروط الخدمة', 'href' => '#terms'],
        ['label' => 'سياسة الكوكيز', 'href' => '#cookies'],
    ],

    'legal_pages' => [
        'privacy' => [
            'title' => 'سياسة الخصوصية',
            'updated_at' => '1 يوليو 2026',
            'content' => 'نلتزم في A2Z Solutions بحماية خصوصية زوار موقعنا وعملائنا. نجمع فقط البيانات الضرورية لتقديم خدماتنا — مثل الاسم والبريد الإلكتروني عند التواصل أو حجز استشارة. لا نبيع بياناتك لأطراف ثالثة. يمكنك طلب حذف بياناتك عبر التواصل معنا على البريد الرسمي.',
        ],
        'terms' => [
            'title' => 'شروط الخدمة',
            'updated_at' => '1 يوليو 2026',
            'content' => 'باستخدامك لموقع A2Z Solutions وخدماتنا، فإنك توافق على شروط الاستخدام هذه. الخدمات تُقدَّم وفق العقود المتفق عليها مع العميل. نحتفظ بحق تعديل المحتوى والأسعار بعد إشعار مسبق. الملكية الفكرية للحلول المُسلَّمة تنتقل للعميل بعد السداد الكامل وفق الاتفاق.',
        ],
        'cookies' => [
            'title' => 'سياسة الكوكيز',
            'updated_at' => '1 يوليو 2026',
            'content' => 'يستخدم موقعنا ملفات تعريف الارتباط (Cookies) لتحسين تجربة التصفح وقياس الأداء. تشمل الكوكيز الضرورية لتشغيل الجلسة والتفضيلات. يمكنك تعطيل الكوكيز من إعدادات المتصفح، لكن قد تتأثر بعض الوظائف.',
        ],
    ],

    'hero' => [
        'badge' => 'رؤية تكنولوجية للمستقبل',
        'title' => 'نصيغ المستقبل من خلال',
        'title_highlight' => 'الابتكار الرقمي',
        'title_suffix' => 'المتميز',
        'description' => 'نحن في A2Z Solutions نقدم حلولاً برمجية متكاملة تجمع بين الفخامة التقنية والدقة التنفيذية لدعم نمو مؤسستك في العصر الرقمي.',
        'image' => 'assets/images/hero-image.webp',
        'image_alt' => 'واجهة رقمية متقدمة تعرض تصورات بيانات معقدة وهياكل برمجية مستقبلية بألوان أزرق داكن وذهبي.',
        'stat' => [
            'value' => '+500',
            'label' => 'مشروع ناجح',
            'icon' => 'rocket_launch',
        ],
    ],

    'services' => [
        'title' => 'خدماتنا المتخصصة',
        'description' => 'نقدم باقة متكاملة من الخدمات التقنية المصممة خصيصاً لتلبية احتياجات المؤسسات الرائدة.',
        'items' => [
            [
                'icon' => 'developer_mode',
                'icon_variant' => 'navy',
                'title' => 'تطوير المواقع الإلكترونية والتطبيقات المتكاملة',
                'description' => 'حلول برمجية فريدة مصممة لتناسب أهداف عملك بدقة متناهية وأداء فائق.',
            ],
            [
                'icon' => 'business_center',
                'icon_variant' => 'teal',
                'title' => 'أنظمة تخطيط موارد المؤسسات',
                'description' => ' تصميم وتطوير أنظمة ERP مخصصة لإدارة موارد المؤسسات. نساعد الشركات على رقمنة أعمالها وربط أقسامها',
            ],
            [
                'icon' => 'brush',
                'icon_variant' => 'gold',
                'title' => 'تصميم واجهات UI/UX',
                'description' => 'تصميم وتطوير واجهات ويب وتطبيقات متكاملة تحسن تجربة المستخدم وتعزز جودة العملية.',
            ],
            [
                'icon' => 'shopping_cart',
                'icon_variant' => 'navy',
                'title' => 'بناء المتاجر الإلكترونية',
                'description' => 'تصميم وتطوير متاجر إلكترونية مبتكرة تعزز مبيعاتك وتعمل على تعزيز العلامة التجارية الخاصة بك.',
            ],
            [
                'icon' => 'cloud_done',
                'icon_variant' => 'teal',
                'title' => 'استضافة المواقع وحجز النطاقات الإلكترونية',
                'description' => 'توفير خدمات استضافة مواقع وحجز النطاقات الإلكترونية لتحسين الأداء والأمان.',
            ],
            [
                'icon' => 'code',
                'icon_variant' => 'gold',
                'title' => 'تحليل النظم وهندسة البرمجيات',
                'description' => 'تحليل النظم وهندسة البرمجيات لتحسين الأداء والأمان.',
            ],

        ],
    ],

    'why_choose_us' => [
        'title' => 'لماذا يختارنا قادة الأعمال؟',
        'description' => 'نحن لا نبني برمجيات فحسب، بل نبني شراكات استراتيجية طويلة الأمد تقوم على الثقة والتميز التقني.',
        'features' => [
            [
                'icon' => 'check_circle',
                'icon_color' => 'gold',
                'title' => 'الالتزام بالمعايير العالمية',
                'description' => 'نتبع أفضل الممارسات الدولية في الجودة والأمان.',
            ],
            [
                'icon' => 'check_circle',
                'icon_color' => 'teal',
                'title' => 'فريق من الخبراء',
                'description' => 'نخبة من المهندسين والمستشارين التقنيين في خدمتك.',
            ],
        ],
        'stats' => [
            [
                'type' => 'large',
                'icon' => 'verified_user',
                'value' => '100%',
                'label' => 'أمان البيانات والخصوصية',
            ],
            [
                'type' => 'small',
                'value' => '24/7',
                'label' => 'دعم فني متميز',
                'variant' => 'teal',
            ],
            [
                'type' => 'small',
                'value' => '3+',
                'label' => 'عاماً من الخبرة',
                'variant' => 'gold',
            ],
        ],
    ],

    'services_page' => [
        'meta_description' => 'اكتشف خدمات A2Z Solutions المتكاملة: تطوير الويب والتطبيقات، أنظمة ERP، UI/UX، التجارة الإلكترونية، الاستضافة، وتحليل النظم.',
        'hero' => [
            'badge' => 'التميز الرقمي',
            'title' => 'حلول برمجية متكاملة',
            'title_line_2' => 'لمستقبل أعمالكم',
            'description' => 'ندمج التكنولوجيا المتطورة مع التصميم الإبداعي لتقديم حلول رقمية مخصصة تدفع نمو مؤسستكم وتضمن ريادتكم في السوق.',
            'primary_cta' => 'ابدأ مشروعك الآن',
            'primary_href' => '/contact',
            'secondary_cta' => 'تصفح سابقة أعمالنا',
            'secondary_href' => '/projects',
        ],
        'bento' => [
            'title' => 'خدماتنا التخصصية',
            'items' => [
                [
                    'layout' => 'featured',
                    'icon' => 'developer_mode',
                    'icon_variant' => 'navy',
                    'decor_icon' => 'code',
                    'title' => 'تطوير المواقع الإلكترونية والتطبيقات المتكاملة',
                    'description' => 'نقوم ببناء منصات ويب قابلة للتوسع وعالية الأداء باستخدام أحدث التقنيات. نركز على السرعة، الأمان، وتجربة المستخدم السلسة لضمان تحقيق أهداف أعمالكم الرقمية.',
                    'features' => [
                        'تطبيقات Laravel & React',
                        'أنظمة إدارة المحتوى (CMS)',
                        'منصات التجارة الإلكترونية',
                        'بوابات الدفع الإلكتروني',
                    ],
                ],
                [
                    'layout' => 'standard',
                    'icon' => 'business_center',
                    'icon_variant' => 'teal',
                    'title' => 'أنظمة تخطيط موارد المؤسسات',
                    'description' => 'تصميم وتطوير أنظمة ERP مخصصة لإدارة موارد المؤسسات وربط أقسامها برقمنة شاملة.',
                    'link_label' => 'اكتشف المزيد',
                    'href' => '#',
                ],
                [
                    'layout' => 'dark',
                    'icon' => 'brush',
                    'icon_variant' => 'gold',
                    'title' => 'تصميم واجهات UI/UX',
                    'description' => 'نبتكر تصميمات تركز على المستخدم وتجمع بين الجمالية والوظيفة لزيادة التفاعل والولاء.',
                    'link_label' => 'اكتشف المزيد',
                    'href' => '#',
                ],
                [
                    'layout' => 'standard',
                    'icon' => 'shopping_cart',
                    'icon_variant' => 'navy',
                    'title' => 'بناء المتاجر الإلكترونية',
                    'description' => 'تصميم وتطوير متاجر إلكترونية مبتكرة تعزز مبيعاتك وتعزز العلامة التجارية الخاصة بك.',
                    'link_label' => 'اكتشف المزيد',
                    'href' => '#',
                ],
                [
                    'layout' => 'standard',
                    'icon' => 'cloud_done',
                    'icon_variant' => 'teal',
                    'title' => 'استضافة المواقع وحجز النطاقات',
                    'description' => 'توفير خدمات استضافة مواقع وحجز النطاقات الإلكترونية لتحسين الأداء والأمان.',
                    'link_label' => 'اكتشف المزيد',
                    'href' => '#',
                ],
                [
                    'layout' => 'wide',
                    'icon' => 'trending_up',
                    'icon_variant' => 'teal',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBK-aDbhl0-LgoEg5PXWJi6UI2qR0lkmu-br3BBF6Mb55LP3z9opZ7yD28e4Gz_P03W4VHRfoHcwDzN1oyEr7GjyZogsMRvL34f4KCWf4BivwF1JP0-JxL4ysNcrrycUQMD8XF5zH1q38nNz2xAY46dB64DWCpGHZnkkkY0lmzWoXAYO6EEuSDpTZUmS_RgS7ju_Pq8gXuKh5_NYsVu0-KqA0ODj_tyB6ERzKioKl01tz_xqGKXplcpTkz5xWCSNfeVIXPkam3C0c4',
                    'image_alt' => 'لوحة تحكم تعرض نمو حركة البحث العضوية بمخططات احترافية.',
                    'title' => 'التحول الرقمي وتحسين الأداء',
                    'description' => 'استراتيجياتنا المدروسة تضمن ظهورك في المقدمة وزيادة الزيارات النوعية لمنصاتك الرقمية بشكل مستدام.',
                    'button_label' => 'طلب استشارة مجانية',
                    'href' => '/contact',
                ],
                [
                    'layout' => 'standard',
                    'icon' => 'code',
                    'icon_variant' => 'gold',
                    'title' => 'تحليل النظم وهندسة البرمجيات',
                    'description' => 'تحليل النظم وهندسة البرمجيات لتحسين الأداء والأمان وبناء بنية تقنية مستدامة.',
                    'link_label' => 'اكتشف المزيد',
                    'href' => '#',
                ],
            ],
        ],
        'faq' => [
            'title' => 'الأسئلة الشائعة',
            'description' => 'كل ما تود معرفته عن خدماتنا وكيفية البدء معنا',
            'items' => [
                [
                    'question' => 'ما هي المدة المتوقعة لتنفيذ مشروع تطوير ويب؟',
                    'answer' => 'تختلف المدة حسب تعقيد المشروع والمتطلبات الوظيفية. بشكل عام، تستغرق المشاريع المتوسطة من 8 إلى 12 أسبوعاً، شاملة مراحل التصميم والتطوير والاختبار.',
                ],
                [
                    'question' => 'هل تقدمون خدمات الدعم الفني بعد إطلاق المشروع؟',
                    'answer' => 'نعم، نحن نؤمن بالشراكة طويلة الأمد. نقدم باقات دعم فني وصيانة دورية تضمن عمل تطبيقك بكفاءة عالية وتحديثه المستمر لمواكبة التطورات التقنية.',
                ],
                [
                    'question' => 'كيف تضمنون أمن البيانات في الحلول السحابية؟',
                    'answer' => 'نعتمد على أفضل البروتوكولات العالمية في التشفير والحماية. جميع حلولنا السحابية متوافقة مع معايير الأمان الدولية ونقوم بإجراء اختبارات اختراق دورية لضمان سلامة بياناتكم.',
                ],
            ],
        ],
        'cta' => [
            'title' => 'هل أنت جاهز للتحول الرقمي؟',
            'description' => 'فريقنا من الخبراء مستعد لتحويل رؤيتك إلى واقع رقمي ملموس. تواصل معنا اليوم لمناقشة مشروعك القادم.',
            'button_label' => 'تواصل مع مستشار تقني',
            'href' => '/contact',
        ],
    ],

    'projects_page' => [
        'meta_description' => 'استعرض مشاريع A2Z Solutions ودراسات الحالة، احسب تكلفة مشروعك التقريبية، واكتشف الحل المناسب لأعمالك عبر مستكشف الحلول الذكي.',
        'hero' => [
            'badge' => 'محفظة الأعمال',
            'title' => 'معرض أعمالنا ودراسات الحالة',
            'description' => 'نحول التحديات التقنية المعقدة إلى حلول برمجية سلسة وفعالة. استعرض مشاريعنا التي قادت التحول الرقمي لعملائنا.',
        ],
        'portfolio' => [
            'title' => 'جميع المشاريع',
            'description' => 'مجموعة مختارة من الحلول التي قدمناها لعملائنا، مع إمكانية التصفية حسب نوع الخدمة.',
        ],
        'filters' => [
            ['slug' => 'all', 'label' => 'الكل'],
            ['slug' => 'web-dev', 'label' => 'المواقع والتطبيقات'],
            ['slug' => 'erp', 'label' => 'أنظمة ERP'],
            ['slug' => 'uiux', 'label' => 'تصميم UI/UX'],
            ['slug' => 'ecommerce', 'label' => 'المتاجر الإلكترونية'],
            ['slug' => 'hosting', 'label' => 'الاستضافة والنطاقات'],
            ['slug' => 'systems', 'label' => 'تحليل النظم'],
        ],
        'items' => [
            [
                'service_type' => 'erp',
                'featured' => true,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnI6LJW4sSMr71di96ssnyork__L3wqkDwvTiyK9JJ7Uwr2gcFeZ6kGP9mJGipVH3ZPllqCTK8k02BUUTEbUqNv20zDZWnrvxc7eCdt5INmm2Md3OdoVWvYCbEQKM9uT8rcfGt9Ip1IIEbxyUTOAEqVnwwJD0RNq-pamX0QaLCMVN_AAYfxaBtiFgJcKTegkKAvbYOvSdQSEGWuB0tlU0nn4G5nEI2uacpRmIX8yBWe1bRbc5ki9p9M2EuInSWpcNdtXMQ86H6e0I',
                'image_alt' => 'لوحة تحكم ERP احترافية تعرض بيانات لوجستية وتحليلات تشغيلية.',
                'tags' => ['Laravel', 'PostgreSQL', 'React'],
                'title' => 'نظام إدارة الموارد اللوجستية',
                'description' => 'تحول رقمي شامل لشركة شحن لربط 50 فرعاً بلوحة تحكم موحدة.',
            ],
            [
                'service_type' => 'ecommerce',
                'featured' => false,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0LGoXmKTt9a7brLBlJ8bJjh-_d6rdLafHFgppyq_anJHzzSvcx1hcmHExea1MLk6c4Cbj4npqZLj2zHzjhh_kE1zFTjljTZsTKIb-2r2hb0es0fK063gulAeRiSoP2yXED_Z8XhFANw4Xg1zOqjmKIO3meewXCl8LjsLdy1esFznY7Du25wtYQ8U1qupBVIfJKjjcVGmMyhzO9Y3UaJO51JsOIVzzyX7Dk_N8Pwf_-EWejL2RPEJ13WIMKR3ZO27BnIyqjtviX64',
                'image_alt' => 'منصة تجارة إلكترونية فاخرة بتصميم عصري وواجهة تسوق تفاعلية.',
                'tags' => ['Next.js', 'Tailwind', 'Stripe'],
                'title' => 'منصة تسوق فخمة',
                'description' => 'بناء تجربة تسوق تفاعلية مع نظام دفع آمن ومتعدد اللغات.',
            ],
            [
                'service_type' => 'web-dev',
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgFmJnR1rxdtz7ZRjNtSJIK-aOKQRwap4SccRaEucG8HltcLOTaT8Nda4JEBVDua3f3syUIIiY2rbCgu0-bjheaF9BrbWGFWLeiNhydc8Pb1I8jQHKxbw5Gd7-eQOs-qyeo8x1go_eqL0sk6WJxpc2GhJu7BmgackvcId7sbq0NY-j3INwdG2Zx2aRJuB3C7VRz7lwtSnYoqjTJDX4uzowlxgjfyHmfNkhlcljRYAjEiGM3GbcLE6DZ1Joz9NLptIRtiBn2LzVe-Y',
                'image_alt' => 'تطبيق جوال صحي يعرض مؤشرات حيوية ومخططات نشاط.',
                'tags' => ['Flutter', 'Firebase', 'Laravel'],
                'title' => 'تطبيق فيت كير الصحي',
                'description' => 'تطبيق جوال لمتابعة المؤشرات الحيوية وربطها بالأطباء المختصين.',
            ],
            [
                'service_type' => 'web-dev',
                'featured' => true,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBDhktjgXgc9WvQbjURjqvDugkiQ7cx4xN2tZk91B3PRoni7p9zaROJzNTdwhenJjQtoXtlf_JyrncPC2GuqfEvjTb0pfyDPqZyReLI49u5Afc1qSqv9cm7VXBWz9BIVLUwd4J_XV0jvNwwOvaQrkhnHJJ5PFizA8pFt_npYv7Yz62XpQ371BgUiXhVha6_nTRxzRribfDOMOrnYUF8D3JqnfDxjTlwU0sIWyLJFNxjpHgGhMPmuBjGYIj6vdyineR7TrVAUZ2hNTQ',
                'image_alt' => 'منصة دفع إلكتروني بتصميم احترافي.',
                'tags' => ['Laravel', 'React', 'API'],
                'title' => 'منصة Nexus Pay',
                'description' => 'نظام دفع إلكتروني متقدم يخدم آلاف المستخدمين يومياً.',
            ],
            [
                'service_type' => 'uiux',
                'featured' => true,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIoqJkfjN3GRj-3yv2JZU9qcxz0t4WkPg-6qJVDQeqBJR9mwgGG5eXK9IuBbqjXyJ0l44mzZNIyg5DtuSW-nn8hi5rWm-__Hso3L7jfs6P0qDiURPTggZn9aL0O3fB5L3B7Kgli9cWygOv0mcfeMRqLiGoAH9fcYGLPQ2E3xx36ozcWrLAgihBKInMWPD44sJDjM8FfTgyIjmasNbXBOOnjuu7lMN_rEXIFc_12w-U6NeDDlvH4VDFwuwh178oKEvLoNPi-tYoW0I',
                'image_alt' => 'تصميم واجهات مستخدم لمنصة لوجستية حديثة.',
                'tags' => ['Figma', 'Design System', 'Prototyping'],
                'title' => 'إعادة تصميم تجربة المستخدم',
                'description' => 'تحسين رحلة المستخدم لمنصة لوجستية وزيادة معدل التحويل بنسبة 32%.',
            ],
            [
                'service_type' => 'hosting',
                'image' => 'assets/images/hero-image.webp',
                'image_alt' => 'بنية سحابية آمنة لاستضافة المواقع والتطبيقات.',
                'tags' => ['Cloud', 'SSL', 'CDN'],
                'title' => 'بنية استضافة سحابية متكاملة',
                'description' => 'نقل واستضافة 12 موقعاً ونطاقاً مع تحسين الأداء والأمان.',
            ],
            [
                'service_type' => 'systems',
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLVs1x2VoeKGbH-w4Uk2-fk_xD3-iG-4GVamjvOR2c1W_4eoJYPluEKdM1czuziFomhgyV81zUZAwgsnVNVwCvlKN0b14ccNqKV-wKW9CnIAEAdudS6EBbuU4YAwbVng0z9MCTmC2zXgTZTlm7Tfv1YF3XZXS_9YIeMLz9YBOSn7_Uubmjt4SM4rJQLceLuuGhxxkS23Xb6CYYcX-h0Ob-Te6g23GCe3gKwskegI7TT-i1_STYEESQE5UZDtRxCcz-q97s4CzylTU',
                'image_alt' => 'مخطط هندسة برمجيات لنظام مؤسسي معقد.',
                'tags' => ['Architecture', 'Microservices', 'DevOps'],
                'title' => 'هندسة نظام مؤسسي متكامل',
                'description' => 'تحليل وإعادة هيكلة بنية تقنية لشركة صناعية كبرى.',
            ],
        ],
        'case_studies' => [
            'badge' => 'دراسات الحالة',
            'title' => 'قصص نجاح من مشاريعنا الفعلية',
            'description' => 'نماذج واقعية من مشاريع نفّذناها في تطوير المواقع وتحليل النظم لهيئات وشركات في سوريا والمنطقة.',
            'items' => [
                [
                    'service_type' => 'web-dev',
                    'service_label' => 'تطوير المواقع والتطبيقات',
                    'focus_type' => 'problem',
                    'client' => 'مركز الشفاء الطبي — إدلب',
                    'duration' => '10 أسابيع',
                    'stack' => ['Laravel 12', 'Vue.js', 'MySQL'],
                    'title' => 'منصة حجز مواعيد طبية متكاملة',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgFmJnR1rxdtz7ZRjNtSJIK-aOKQRwap4SccRaEucG8HltcLOTaT8Nda4JEBVDua3f3syUIIiY2rbCgu0-bjheaF9BrbWGFWLeiNhydc8Pb1I8jQHKxbw5Gd7-eQOs-qyeo8x1go_eqL0sk6WJxpc2GhJu7BmgackvcId7sbq0NY-j3INwdG2Zx2aRJuB3C7VRz7lwtSnYoqjTJDX4uzowlxgjfyHmfNkhlcljRYAjEiGM3GbcLE6DZ1Joz9NLptIRtiBn2LzVe-Y',
                    'image_alt' => 'واجهة تطبيق حجز مواعيد طبية تعرض جدول المواعيد والمؤشرات الصحية.',
                    'highlight' => ['value' => '-38%', 'label' => 'تقليل الغياب'],
                    'problem' => 'كان المركز يعتمد على الحجز الهاتفي والدفاتر الورقية، مما أدى إلى ازدحام الاستقبال، تضارب المواعيد، وغياب 4 من كل 10 مرضى عن مواعيدهم دون إشعار مسبق.',
                    'solution' => 'بنينا بوابة ويب متجاوبة مع نظام حجز ذكي يرسل تذكيرات عبر SMS وواتساب، ولوحة تحكم للأطباء لإدارة الجداول. استخدمنا Laravel للواجهة الخلفية مع جدولة مهام تلقائية وتكامل مع تقويم Google.',
                    'results' => [
                        ['value' => '-38%', 'label' => 'نسبة الغياب'],
                        ['value' => '+2.4x', 'label' => 'سرعة الحجز'],
                    ],
                ],
                [
                    'service_type' => 'systems',
                    'service_label' => 'تحليل النظم وهندسة البرمجيات',
                    'focus_type' => 'goal',
                    'goal' => 'توحيد إدارة 6 مستودعات في نظام واحد مع تتبع لحظي لحركة المخزون وربطها بالمحاسبة.',
                    'actions_taken' => 'أجرينا تحليلاً شاملاً للعمليات (BPMN)، ثم صممنا بنية موحدة بطبقة API مركزية تربط المستودعات بنظام المحاسبة. أعدنا نمذجة قاعدة البيانات مع تتبع لحظي لحركة كل صنف وصلاحيات وصول حسب الدور.',
                    'client' => 'شركة النور للتوزيع — حلب',
                    'duration' => '14 أسبوعاً',
                    'stack' => ['تحليل BPMN', 'PostgreSQL', 'REST API'],
                    'title' => 'إعادة هندسة نظام إدارة المخزون',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLVs1x2VoeKGbH-w4Uk2-fk_xD3-iG-4GVamjvOR2c1W_4eoJYPluEKdM1czuziFomhgyV81zUZAwgsnVNVwCvlKN0b14ccNqKV-wKW9CnIAEAdudS6EBbuU4YAwbVng0z9MCTmC2zXgTZTlm7Tfv1YF3XZXS_9YIeMLz9YBOSn7_Uubmjt4SM4rJQLceLuuGhxxkS23Xb6CYYcX-h0Ob-Te6g23GCe3gKwskegI7TT-i1_STYEESQE5UZDtRxCcz-q97s4CzylTU',
                    'image_alt' => 'لوحة تحكم مخزون تعرض حركة البضائع والتنبيهات التشغيلية.',
                    'highlight' => ['value' => '-52%', 'label' => 'أخطاء المخزون'],
                    'problem' => 'كانت الشركة تدير 6 مستودعات عبر 3 أنظمة منفصلة (Excel، برنامج محاسبة قديم، وتطبيق جوال غير متزامن). النتيجة: فروقات مخزون شهرية تصل إلى 18% وتأخر في تسليم الطلبات للموزعين.',
                    'solution' => 'أجرينا تحليلاً شاملاً للعمليات (BPMN)، ثم صممنا بنية موحدة بطبقة API مركزية تربط المستودعات بنظام المحاسبة. أعدنا نمذجة قاعدة البيانات مع تتبع لحظي لحركة كل صنف وصلاحيات وصول حسب الدور.',
                    'results' => [
                        ['value' => '-52%', 'label' => 'أخطاء الجرد'],
                        ['value' => '6→1', 'label' => 'نظام موحد'],
                    ],
                ],
                [
                    'service_type' => 'web-dev',
                    'service_label' => 'تطوير المواقع والتطبيقات',
                    'focus_type' => 'goal',
                    'goal' => 'رقمنة طلبات الدعم والتطوع وإعداد تقارير دورية للجهات المانحة بشكل آلي.',
                    'actions_taken' => 'طورنا موقعاً ثنائي اللغة (عربي/إنجليزي) مع نماذج طلبات ذكية، لوحة إدارة Filament لتتبع حالة كل طلب، وتصدير تقارير Excel تلقائية. ربطنا النماذج بإشعارات بريدية فورية لفريق العمل.',
                    'client' => 'جمعية كفاءة التنموية — إدلب',
                    'duration' => '8 أسابيع',
                    'stack' => ['Laravel 12', 'Tailwind CSS', 'Filament'],
                    'title' => 'بوابة خدمات إلكترونية للجمعيات',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0LGoXmKTt9a7brLBlJ8bJjh-_d6rdLafHFgppyq_anJHzzSvcx1hcmHExea1MLk6c4Cbj4npqZLj2zHzjhh_kE1zFTjljTZsTKIb-2r2hb0es0fK063gulAeRiSoP2yXED_Z8XhFANw4Xg1zOqjmKIO3meewXCl8LjsLdy1esFznY7Du25wtYQ8U1qupBVIfJKjjcVGmMyhzO9Y3UaJO51JsOIVzzyX7Dk_N8Pwf_-EWejL2RPEJ13WIMKR3ZO27BnIyqjtviX64',
                    'image_alt' => 'بوابة خدمات إلكترونية بتصميم عربي واضح لطلبات الدعم والتبرعات.',
                    'highlight' => ['value' => '+65%', 'label' => 'طلبات رقمية'],
                    'problem' => 'كانت الجمعية تتلقى طلبات الدعم والتطوع عبر فيسبوك والاتصالات الهاتفية دون أرشفة، مما صعّب متابعة الحالات وإعداد التقارير الدورية للجهات المانحة.',
                    'solution' => 'طورنا موقعاً ثنائي اللغة (عربي/إنجليزي) مع نماذج طلبات ذكية، لوحة إدارة Filament لتتبع حالة كل طلب، وتصدير تقارير Excel تلقائية. ربطنا النماذج بإشعارات بريدية فورية لفريق العمل.',
                    'results' => [
                        ['value' => '+65%', 'label' => 'طلبات عبر الموقع'],
                        ['value' => '-70%', 'label' => 'وقت المعالجة'],
                    ],
                ],
                [
                    'service_type' => 'systems',
                    'service_label' => 'تحليل النظم وهندسة البرمجيات',
                    'client' => 'مؤسسة الأمان التجارية — دمشق',
                    'duration' => '16 أسبوعاً',
                    'stack' => ['UML', 'Docker', 'Laravel API'],
                    'title' => 'دمج 4 أنظمة قديمة في منصة واحدة',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnI6LJW4sSMr71di96ssnyork__L3wqkDwvTiyK9JJ7Uwr2gcFeZ6kGP9mJGipVH3ZPllqCTK8k02BUUTEbUqNv20zDZWnrvxc7eCdt5INmm2Md3OdoVWvYCbEQKM9uT8rcfGt9Ip1IIEbxyUTOAEqVnwwJD0RNq-pamX0QaLCMVN_AAYfxaBtiFgJcKTegkKAvbYOvSdQSEGWuB0tlU0nn4G5nEI2uacpRmIX8yBWe1bRbc5ki9p9M2EuInSWpcNdtXMQ86H6e0I',
                    'image_alt' => 'مخطط بنية تقنية يوضح دمج أنظمة المبيعات والمخزون والمحاسبة.',
                    'highlight' => ['value' => '-40%', 'label' => 'تكلفة تشغيل'],
                    'problem' => 'المؤسسة كانت تدفع اشتراكات 4 برامج منفصلة (مبيعات، مخزون، محاسبة، CRM) مع تكرار إدخال البيانات يدوياً بينها. فريق المحاسبة يقضي 12 ساعة أسبوعياً في مطابقة الأرقام.',
                    'solution' => 'بدأنا بورش تحليل مع أصحاب المصلحة، ثم صممنا طبقة تكامل (Integration Layer) عبر REST API تزامن البيانات بين الأنظمة دون إيقاف العمل. أعدنا هيكلة قواعد البيانات ووثّقنا 47 نقطة تكامل مع اختبارات آلية.',
                    'results' => [
                        ['value' => '-40%', 'label' => 'تكلفة التشغيل'],
                        ['value' => '12→2', 'label' => 'ساعات مطابقة/أسبوع'],
                    ],
                ],
                [
                    'service_type' => 'web-dev',
                    'service_label' => 'تطوير المواقع والتطبيقات',
                    'client' => 'أكاديمية المستقبل — حماة',
                    'duration' => '12 أسبوعاً',
                    'stack' => ['Laravel 12', 'Livewire', 'AWS S3'],
                    'title' => 'منصة تعليمية تفاعلية مع لوحة تحكم',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBDhktjgXgc9WvQbjURjqvDugkiQ7cx4xN2tZk91B3PRoni7p9zaROJzNTdwhenJjQtoXtlf_JyrncPC2GuqfEvjTb0pfyDPqZyReLI49u5Afc1qSqv9cm7VXBWz9BIVLUwd4J_XV0jvNwwOvaQrkhnHJJ5PFizA8pFt_npYv7Yz62XpQ371BgUiXhVha6_nTRxzRribfDOMOrnYUF8D3JqnfDxjTlwU0sIWyLJFNxjpHgGhMPmuBjGYIj6vdyineR7TrVAUZ2hNTQ',
                    'image_alt' => 'منصة تعليم إلكتروني تعرض دورات وفيديوهات ولوحة تقدم الطلاب.',
                    'highlight' => ['value' => '+320', 'label' => 'طالب نشط'],
                    'problem' => 'الأكاديمية كانت تنشر الدروس عبر تيليغرام ويوتيوب دون تتبع تقدم الطلاب أو نظام اختبارات. معدل إكمال الدورات لم يتجاوز 22% ولم يكن هناك مصدر دخل مستدام.',
                    'solution' => 'أنشأنا منصة تعليمية كاملة: تسجيل طلاب، دورات بفيديو محمي، اختبارات تفاعلية، شهادات PDF تلقائية، ولوحة تحكم للمدربين. استضفنا المحتوى على S3 مع بث تدريجي (HLS) لضمان سرعة التحميل في الشبكات الضعيفة.',
                    'results' => [
                        ['value' => '+320', 'label' => 'طالب مسجل'],
                        ['value' => '22→61%', 'label' => 'إكمال الدورات'],
                    ],
                ],
                [
                    'service_type' => 'systems',
                    'service_label' => 'تحليل النظم وهندسة البرمجيات',
                    'client' => 'مصنع الأمل للصناعات — إدلب',
                    'duration' => '18 أسبوعاً',
                    'stack' => ['تحليل العمليات', 'Laravel', 'IoT Gateway'],
                    'title' => 'رقمنة خط الإنتاج وربطه بلوحة تحكم',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQrTGBmZzCQ5X7geSF4HjMfz5Pq92hbvNjO2azst0SiBGh4HoUTdpiNhfuPL4VgxxMQZ0nHW0_gg2f_pwxlgV2b5z-jNTnDXr50qAuuzjBz7FvRZPuSV-xs1irR2GV9HPLgJqrZWeu9t67Ai1DVobYXe8KcxmY47nVTLO_Q8bGxIONtAXhr2TsvNoqwcMDCjFstA7_njrLPMYJcGEaVaGp5f7NO8iOxG9BxPywPdimJx-4b6RtcIm8FTYjg6drqUcWWCdyw4jXpsk',
                    'image_alt' => 'لوحة تحكم صناعية تعرض مؤشرات الإنتاج وخطوط التصنيع.',
                    'highlight' => ['value' => '+45%', 'label' => 'كفاءة الإنتاج'],
                    'problem' => 'المصنع كان يسجل الإنتاج يدوياً في نهاية كل وردية. مدير الإنتاج لا يرى الأعطال إلا بعد 8 ساعات، والتقارير الأسبوعية تُعد يدوياً من 3 مصادر مختلفة.',
                    'solution' => 'حللنا دورة الإنتاج كاملة، ثم ربطنا عدادات الآلات ببوابة IoT ترسل البيانات كل 5 دقائق إلى لوحة ويب Laravel. صممنا تقارير آلية للإنتاج والهدر مع تنبيهات فورية عند توقف أي خط.',
                    'results' => [
                        ['value' => '+45%', 'label' => 'كفاءة الإنتاج'],
                        ['value' => '8→15 د', 'label' => 'اكتشاف الأعطال'],
                    ],
                ],
            ],
        ],
        'solutions_finder' => [
            'title' => 'مستكشف الحلول',
            'description' => 'أجب على بضعة أسئلة سريعة لنقترح عليك الخدمة الأنسب لاحتياجات عملك.',
            'steps' => [
                [
                    'id' => 'goal',
                    'question' => 'ما هو هدفك الرئيسي؟',
                    'options' => [
                        ['value' => 'presence', 'label' => 'بناء حضور رقمي', 'icon' => 'language', 'scores' => ['web-dev' => 3, 'uiux' => 2]],
                        ['value' => 'sales', 'label' => 'زيادة المبيعات أونلاين', 'icon' => 'shopping_cart', 'scores' => ['ecommerce' => 3, 'web-dev' => 2, 'uiux' => 1]],
                        ['value' => 'operations', 'label' => 'إدارة العمليات الداخلية', 'icon' => 'business_center', 'scores' => ['erp' => 3, 'systems' => 2]],
                        ['value' => 'infrastructure', 'label' => 'تحسين البنية التحتية', 'icon' => 'cloud_done', 'scores' => ['hosting' => 3, 'systems' => 2]],
                    ],
                ],
                [
                    'id' => 'size',
                    'question' => 'ما حجم مؤسستك؟',
                    'options' => [
                        ['value' => 'startup', 'label' => 'ناشئة / فردية', 'icon' => 'rocket_launch', 'scores' => ['web-dev' => 2, 'uiux' => 2, 'hosting' => 1]],
                        ['value' => 'smb', 'label' => 'شركة متوسطة', 'icon' => 'corporate_fare', 'scores' => ['erp' => 2, 'ecommerce' => 2, 'web-dev' => 1]],
                        ['value' => 'enterprise', 'label' => 'مؤسسة كبرى', 'icon' => 'hub', 'scores' => ['erp' => 3, 'systems' => 3, 'web-dev' => 1]],
                    ],
                ],
                [
                    'id' => 'priority',
                    'question' => 'ما أولويتك الآن؟',
                    'options' => [
                        ['value' => 'speed', 'label' => 'إطلاق سريع', 'icon' => 'bolt', 'scores' => ['web-dev' => 3, 'uiux' => 2]],
                        ['value' => 'scale', 'label' => 'قابلية التوسع', 'icon' => 'trending_up', 'scores' => ['erp' => 3, 'systems' => 2, 'ecommerce' => 1]],
                        ['value' => 'design', 'label' => 'تجربة مستخدم مميزة', 'icon' => 'brush', 'scores' => ['uiux' => 3, 'web-dev' => 1, 'ecommerce' => 1]],
                    ],
                ],
            ],
            'services_map' => [
                'web-dev' => ['title' => 'تطوير المواقع والتطبيقات', 'icon' => 'developer_mode', 'description' => 'منصات ويب وتطبيقات متكاملة عالية الأداء.'],
                'erp' => ['title' => 'أنظمة تخطيط موارد المؤسسات', 'icon' => 'business_center', 'description' => 'رقمنة العمليات وربط الأقسام في نظام واحد.'],
                'uiux' => ['title' => 'تصميم واجهات UI/UX', 'icon' => 'brush', 'description' => 'تصاميم تركز على المستخدم وتعزز التفاعل.'],
                'ecommerce' => ['title' => 'بناء المتاجر الإلكترونية', 'icon' => 'shopping_cart', 'description' => 'متاجر إلكترونية آمنة مع بوابات دفع متعددة.'],
                'hosting' => ['title' => 'الاستضافة وحجز النطاقات', 'icon' => 'cloud_done', 'description' => 'استضافة آمنة وسريعة مع إدارة النطاقات.'],
                'systems' => ['title' => 'تحليل النظم وهندسة البرمجيات', 'icon' => 'code', 'description' => 'بنية تقنية مستدامة وتحسين الأداء والأمان.'],
            ],
            'services_href' => '/services',
            'quote_href' => '#quote-request',
        ],
        'calculator' => [
            'title' => 'حاسبة التكلفة التفاعلية',
            'description' => 'احصل على تقدير فوري تقريبي لتكلفة مشروعك بناءً على نوع الخدمة والميزات المطلوبة.',
            'disclaimer' => 'هذا السعر تقديري وقد يتغير بناءً على تحليل المتطلبات الدقيق.',
            'services_cta' => ['label' => 'عرض جميع الخدمات', 'href' => '/services'],
            'quote_cta' => ['label' => 'طلب استشارة مجانية', 'href' => '#quote-request'],
            'service_types' => [
                ['slug' => 'web-dev', 'icon' => 'developer_mode', 'title' => 'تطوير المواقع والتطبيقات', 'description' => 'مواقع، تطبيقات، ولوحات تحكم متكاملة.', 'base_price' => 3500],
                ['slug' => 'erp', 'icon' => 'business_center', 'title' => 'أنظمة ERP', 'description' => 'أنظمة إدارة مؤسسية مخصصة.', 'base_price' => 12000],
                ['slug' => 'uiux', 'icon' => 'brush', 'title' => 'تصميم UI/UX', 'description' => 'تصميم واجهات وتجربة مستخدم.', 'base_price' => 2000],
                ['slug' => 'ecommerce', 'icon' => 'shopping_cart', 'title' => 'المتاجر الإلكترونية', 'description' => 'منصات تجارة إلكترونية شاملة.', 'base_price' => 5000],
                ['slug' => 'hosting', 'icon' => 'cloud_done', 'title' => 'الاستضافة والنطاقات', 'description' => 'استضافة مواقع وحجز نطاقات.', 'base_price' => 500],
                ['slug' => 'systems', 'icon' => 'code', 'title' => 'تحليل النظم', 'description' => 'هندسة برمجيات وبنية تقنية.', 'base_price' => 8000],
            ],
            'features' => [
                ['id' => 'auth', 'title' => 'نظام تسجيل دخول ومستخدمين', 'description' => 'تأمين البيانات وملفات شخصية.', 'price' => 1500],
                ['id' => 'payment', 'title' => 'بوابة دفع إلكتروني', 'description' => 'تكامل مع بوابات دفع محلية وعالمية.', 'price' => 3000],
                ['id' => 'multilang', 'title' => 'دعم لغات متعددة', 'description' => 'عربي، إنجليزي، وواجهات RTL/LTR.', 'price' => 1200],
                ['id' => 'notifications', 'title' => 'إشعارات فورية', 'description' => 'بريد إلكتروني وإشعارات تطبيق.', 'price' => 800],
                ['id' => 'api', 'title' => 'تكامل مع أنظمة خارجية', 'description' => 'ربط API مع أنظمة الطرف الثالث.', 'price' => 4000],
                ['id' => 'analytics', 'title' => 'تحليلات ولوحات بيانات', 'description' => 'تقارير تفاعلية ومؤشرات أداء.', 'price' => 2500],
            ],
            'scales' => [
                ['slug' => 'small', 'icon' => 'rocket_launch', 'title' => 'مشروع ناشئ', 'description' => 'MVP مع الميزات الأساسية.', 'multiplier' => 1],
                ['slug' => 'medium', 'icon' => 'corporate_fare', 'title' => 'مشروع متوسط', 'description' => 'توسيع نطاق وتجربة مخصصة.', 'multiplier' => 1.5],
                ['slug' => 'large', 'icon' => 'hub', 'title' => 'مشروع مؤسسي', 'description' => 'بنية معقدة وأمان عالي.', 'multiplier' => 2.5],
            ],
        ],
        'quote' => [
            'title' => 'طلب عرض سعر',
            'description' => 'أخبرنا عن مشروعك وسيتواصل معك فريقنا خلال 24 ساعة بعرض مفصل.',
            'subjects' => [
                'استفسار عام',
                'طلب عرض سعر',
                'دراسة حالة / مشروع سابق',
                'شراكة استراتيجية',
            ],
            'submit_label' => 'إرسال الطلب',
        ],
        'cta' => [
            'title' => 'هل أنت مستعد لمشروعك القادم؟',
            'description' => 'دعنا نساعدك في تحويل رؤيتك إلى واقع رقمي ملموس. فريقنا من الخبراء جاهز للبدء معك اليوم.',
            'primary_label' => 'احجز استشارة مجانية',
            'primary_href' => '#quote-request',
            'secondary_label' => 'تواصل معنا',
            'secondary_href' => '/contact',
        ],
    ],

    'projects' => [
        'title' => ' مشاريعنا المميزة',
        'description' => 'قصص نجاح سطرناها مع شركائنا حول العالم.',
        'view_all_label' => 'عرض جميع المشاريع',
        'view_all_href' => '/projects',
        'items' => [
            [
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBDhktjgXgc9WvQbjURjqvDugkiQ7cx4xN2tZk91B3PRoni7p9zaROJzNTdwhenJjQtoXtlf_JyrncPC2GuqfEvjTb0pfyDPqZyReLI49u5Afc1qSqv9cm7VXBWz9BIVLUwd4J_XV0jvNwwOvaQrkhnHJJ5PFizA8pFt_npYv7Yz62XpQ371BgUiXhVha6_nTRxzRribfDOMOrnYUF8D3JqnfDxjTlwU0sIWyLJFNxjpHgGhMPmuBjGYIj6vdyineR7TrVAUZ2hNTQ',
                'image_alt' => 'لوحة تحكم لمنصة تكنولوجيا مالية بتصميم احترافي بألوان أزرق داكن وذهبي.',
                'category' => 'قطاع التكنولوجيا المالية',
                'category_variant' => 'gold',
                'title' => 'منصة Nexus Pay',
                'description' => 'نظام دفع إلكتروني متقدم يخدم آلاف المستخدمين يومياً.',
            ],
            [
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIoqJkfjN3GRj-3yv2JZU9qcxz0t4WkPg-6qJVDQeqBJR9mwgGG5eXK9IuBbqjXyJ0l44mzZNIyg5DtuSW-nn8hi5rWm-__Hso3L7jfs6P0qDiURPTggZn9aL0O3fB5L3B7Kgli9cWygOv0mcfeMRqLiGoAH9fcYGLPQ2E3xx36ozcWrLAgihBKInMWPD44sJDjM8FfTgyIjmasNbXBOOnjuu7lMN_rEXIFc_12w-U6NeDDlvH4VDFwuwh178oKEvLoNPi-tYoW0I',
                'image_alt' => 'برنامج إدارة لوجستية معروض على شاشات احترافية في مركز تحكم حديث.',
                'category' => 'الخدمات اللوجستية',
                'category_variant' => 'teal',
                'title' => 'نظام إدارة الأسطول الذكي',
                'description' => 'تحسين كفاءة سلاسل الإمداد باستخدام الذكاء الاصطناعي.',
            ],
            [
                'image' => 'assets/images/hero-image.webp',
                'image_alt' => 'نظام سجلات طبية مستقبلي يعرض نماذج بيولوجية ثلاثية الأبعاد وبيانات المرضى.',
                'category' => 'الرعاية الصحية',
                'category_variant' => 'gold',
                'title' => 'منصة الرعاية الصحية الرقمية',
                'description' => 'حلول متكاملة لرقمنة السجلات الطبية وتحسين تجربة المرضى.',
            ],
        ],
    ],

    'contact_page' => [
        'meta_description' => 'تواصل مع A2Z Solutions — البريد الإلكتروني، واتساب، الموقع، نموذج التواصل، وحجز استشارة مجانية.',
        'hero' => [
            'title' => 'دعنا نبني المستقبل معاً',
            'description' => 'نحن هنا لتحويل أفكارك الطموحة إلى واقع رقمي ملموس. فريقنا من الخبراء جاهز لمناقشة مشروعك القادم وتقديم حلول تقنية مبتكرة تتجاوز التوقعات.',
        ],
        'info_cards' => [
            [
                'icon' => 'mail',
                'icon_variant' => 'navy',
                'title' => 'البريد الإلكتروني',
                'value' => 'ahmadqatea023@gmail.com',
                'note' => 'نرد خلال 24 ساعة',
                'href' => 'mailto:ahmadqatea023@gmail.com',
                'border' => 'navy',
            ],
            [
                'icon' => 'chat',
                'icon_variant' => 'teal',
                'title' => 'اتصل بنا',
                'value' => '+963993511250',
                'note' => 'متاح عبر واتساب',
                'href' => 'https://wa.me/963993511250',
                'border' => 'teal',
                'external' => true,
            ],
            [
                'icon' => 'location_on',
                'icon_variant' => 'gold',
                'title' => 'المقر الرئيسي',
                'value' => 'سوريا، محافظة إدلب، كرباط',
                'note' => 'زيارات بموعد مسبق',
                'href' => 'https://www.google.com/maps?q=35.93842120265023,36.64029414273561',
                'border' => 'gold',
                'external' => true,
            ],
            [
                'icon' => 'groups',
                'icon_variant' => 'slate',
                'title' => 'تابعنا',
                'value' => 'A2Z Solutions',
                'note' => 'آخر التحديثات التقنية',
                'href' => 'https://www.facebook.com/',
                'border' => 'slate',
                'external' => true,
            ],
        ],
        'form' => [
            'title' => 'نموذج التواصل',
            'description' => 'أخبرنا بالمزيد عن مشروعك وسنقوم بالرد عليك في أقرب وقت.',
            'submit_label' => 'إرسال الرسالة',
            'project_types' => [
                'تطوير مواقع وتطبيقات',
                'أنظمة ERP',
                'تصميم UI/UX',
                'متجر إلكتروني',
                'استضافة ونطاقات',
                'تحليل النظم',
                'أخرى',
            ],
        ],
        'booking' => [
            'title' => 'حجز موعد استشارة',
            'description' => 'اختر الوقت المناسب لك للتحدث مع أحد خبرائنا التقنيين (30 دقيقة).',
            'confirm_label' => 'تأكيد الموعد عبر واتساب',
            'whatsapp_message' => 'مرحباً، أود حجز موعد استشارة مع A2Z Solutions',
        ],
        'map' => [
            'title' => 'تفضل بزيارتنا',
            'description' => 'نسعد باستقبال شركائنا في مقرنا بمحافظة إدلب لمناقشة المشاريع وجهاً لوجه.',
            'hours_label' => 'ساعات العمل',
            'hours' => 'الأحد - الخميس: 9ص - 6م',
            'button_label' => 'افتح في خرائط جوجل',
        ],
        'cta' => [
            'title' => 'جاهز لبدء مشروعك؟',
            'description' => 'لا تتردد في التواصل — استشارتنا الأولى مجانية وبدون التزام.',
            'button_label' => 'احجز استشارة الآن',
            'href' => '#booking',
        ],
    ],

    'knowledge_page' => [
        'meta_description' => 'مركز المعرفة في A2Z Solutions — مدونة تقنية، أدلة تعليمية، ومعلومات عن الشركة وخبراتنا.',
        'hero' => [
            'badge' => 'مركز المعرفة',
            'title' => 'نشارككم الخبرة والمعرفة',
            'description' => 'مدونة تقنية، أدلة عملية، وقصة فريقنا — كل ما تحتاجه لفهم عالم التحول الرقمي واتخاذ قرارات تقنية واثقة.',
        ],
        'sections_nav' => [
            ['id' => 'about', 'label' => 'عن الشركة', 'icon' => 'business'],
            ['id' => 'blog', 'label' => 'المدونة', 'icon' => 'article'],
            ['id' => 'tutorials', 'label' => 'التعليمات', 'icon' => 'school'],
        ],
        'about' => [
            'badge' => 'من نحن',
            'title' => 'عن A2Z Solutions',
            'description' => 'شركة سورية متخصصة في تطوير البرمجيات وتحليل النظم، نقدم حلولاً رقمية مخصصة للمؤسسات والشركات الناشئة في سوريا والمنطقة.',
            'mission' => 'تمكين الأعمال من التحول الرقمي عبر حلول برمجية موثوقة، قابلة للتوسع، ومصممة وفق احتياجات السوق المحلي.',
            'vision' => 'أن نكون الشريك التقني الأول للمؤسسات التي تسعى للابتكار والنمو في العصر الرقمي.',
            'image' => 'assets/images/hero-image.webp',
            'image_alt' => 'فريق A2Z Solutions يعمل على حلول برمجية متقدمة.',
            'values' => [
                ['icon' => 'verified', 'title' => 'الجودة والدقة', 'description' => 'كل سطر كود يخضع لمعايير مراجعة صارمة.'],
                ['icon' => 'handshake', 'title' => 'الشراكة طويلة الأمد', 'description' => 'نبني علاقات ثقة مع عملائنا لا مشاريع مؤقتة.'],
                ['icon' => 'lightbulb', 'title' => 'الابتكار المستمر', 'description' => 'نواكب أحدث التقنيات ونطبقها بحلول عملية.'],
            ],
            'stats' => [
                ['value' => '3+', 'label' => 'سنوات خبرة'],
                ['value' => '+50', 'label' => 'مشروع منجز'],
                ['value' => '24/7', 'label' => 'دعم فني'],
            ],
        ],
        'blog' => [
            'title' => 'المدونة التقنية',
            'description' => 'مقالات وتحليلات حول تطوير الويب، أنظمة الأعمال، وأفضل الممارسات التقنية.',
            'posts' => [
                [
                    'title' => 'لماذا Laravel 12 الخيار الأمثل للمشاريع السورية؟',
                    'category' => 'تطوير الويب',
                    'date' => '15 مارس 2026',
                    'read_time' => '6 دقائق',
                    'excerpt' => 'نستعرض مميزات Laravel 12 وكيف يساعد الشركات المحلية على بناء أنظمة آمنة وقابلة للتوسع بتكلفة معقولة.',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBDhktjgXgc9WvQbjURjqvDugkiQ7cx4xN2tZk91B3PRoni7p9zaROJzNTdwhenJjQtoXtlf_JyrncPC2GuqfEvjTb0pfyDPqZyReLI49u5Afc1qSqv9cm7VXBWz9BIVLUwd4J_XV0jvNwwOvaQrkhnHJJ5PFizA8pFt_npYv7Yz62XpQ371BgUiXhVha6_nTRxzRribfDOMOrnYUF8D3JqnfDxjTlwU0sIWyLJFNxjpHgGhMPmuBjGYIj6vdyineR7TrVAUZ2hNTQ',
                    'image_alt' => 'مقال تقني عن Laravel وبيئة التطوير.',
                ],
                [
                    'title' => 'دليل التحول الرقمي للمؤسسات الصغيرة',
                    'category' => 'التحول الرقمي',
                    'date' => '2 مارس 2026',
                    'read_time' => '8 دقائق',
                    'excerpt' => 'خطوات عملية لرقمنة عملياتك دون ميزانية ضخمة — من الفواتير الورقية إلى أنظمة إدارة متكاملة.',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLVs1x2VoeKGbH-w4Uk2-fk_xD3-iG-4GVamjvOR2c1W_4eoJYPluEKdM1czuziFomhgyV81zUZAwgsnVNVwCvlKN0b14ccNqKV-wKW9CnIAEAdudS6EBbuU4YAwbVng0z9MCTmC2zXgTZTlm7Tfv1YF3XZXS_9YIeMLz9YBOSn7_Uubmjt4SM4rJQLceLuuGhxxkS23Xb6CYYcX-h0Ob-Te6g23GCe3gKwskegI7TT-i1_STYEESQE5UZDtRxCcz-q97s4CzylTU',
                    'image_alt' => 'مقال عن التحول الرقمي للمؤسسات.',
                ],
                [
                    'title' => 'أمان البيانات: ما يجب أن تعرفه قبل إطلاق موقعك',
                    'category' => 'الأمن السيبراني',
                    'date' => '20 فبراير 2026',
                    'read_time' => '5 دقائق',
                    'excerpt' => 'أساسيات حماية بيانات العملاء — من شهادات SSL إلى أفضل ممارسات التخزين والنسخ الاحتياطي.',
                    'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQrTGBmZzCQ5X7geSF4HjMfz5Pq92hbvNjO2azst0SiBGh4HoUTdpiNhfuPL4VgxxMQZ0nHW0_gg2f_pwxlgV2b5z-jNTnDXr50qAuuzjBz7FvRZPuSV-xs1irR2GV9HPLgJqrZWeu9t67Ai1DVobYXe8KcxmY47nVTLO_Q8bGxIONtAXhr2TsvNoqwcMDCjFstA7_njrLPMYJcGEaVaGp5f7NO8iOxG9BxPywPdimJx-4b6RtcIm8FTYjg6drqUcWWCdyw4jXpsk',
                    'image_alt' => 'مقال عن أمان البيانات والحماية.',
                ],
            ],
        ],
        'tutorials' => [
            'title' => 'التعليمات والأدلة',
            'description' => 'شروحات عملية خطوة بخطوة لمساعدتك على فهم خدماتنا وإدارة مشاريعك التقنية.',
            'items' => [
                [
                    'icon' => 'rocket_launch',
                    'title' => 'كيف تبدأ مشروعك معنا؟',
                    'level' => 'مبتدئ',
                    'duration' => '10 دقائق',
                    'steps' => ['تواصل معنا', 'جلسة استكشاف', 'عرض سعر', 'التطوير', 'التسليم والدعم'],
                    'excerpt' => 'دليل سريع يوضح رحلة العميل من أول تواصل حتى إطلاق المشروع.',
                ],
                [
                    'icon' => 'description',
                    'title' => 'إعداد متطلبات مشروع الويب',
                    'level' => 'متوسط',
                    'duration' => '15 دقيقة',
                    'steps' => ['تحديد الأهداف', 'قائمة الصفحات', 'الميزات المطلوبة', 'التصميم المرجعي'],
                    'excerpt' => 'كيف تُعد وثيقة متطلبات واضحة تسرّع التطوير وتقلل التكاليف.',
                ],
                [
                    'icon' => 'cloud_done',
                    'title' => 'دليل الاستضافة وإدارة النطاق',
                    'level' => 'مبتدئ',
                    'duration' => '8 دقائق',
                    'steps' => ['اختيار النطاق', 'إعداد الاستضافة', 'ربط البريد', 'النسخ الاحتياطي'],
                    'excerpt' => 'كل ما تحتاج معرفته عن استضافة موقعك وحجز نطاقك بشكل صحيح.',
                ],
                [
                    'icon' => 'support_agent',
                    'title' => 'الدعم الفني بعد الإطلاق',
                    'level' => 'جميع المستويات',
                    'duration' => '5 دقائق',
                    'steps' => ['قنوات التواصل', 'أوقات الاستجابة', 'الصيانة الدورية', 'التحديثات'],
                    'excerpt' => 'كيف نضمن استمرارية عمل نظامك بعد التسليم مع دعم فني موثوق.',
                ],
            ],
        ],
        'cta' => [
            'title' => 'هل لديك سؤال تقني؟',
            'description' => 'فريقنا مستعد للإجابة على استفساراتك ومساعدتك في اختيار الحل المناسب.',
            'button_label' => 'تواصل معنا',
            'href' => '/contact',
        ],
    ],

    'cta' => [
        'title' => 'هل أنت مستعد لبدء',
        'title_highlight' => 'رحلة التحول الرقمي؟',
        'description' => 'تواصل مع خبرائنا اليوم لمناقشة كيف يمكن لـ A2Z Solutions أن ترتقي بأعمالك إلى آفاق جديدة.',
        'button_label' => 'استشارة مجانية',
    ],

];
